import = [
  "~/.config/alacritty/a-theme/themes/tokyo-night-storm.toml"
]

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1.0

[window.padding]
x = 6
y = 0


[cursor]
style = "Beam"

[font]
size = 11.5

[font.normal]
family = "MesloLGS NF"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
